/* Generated by bootstrap.py — the publishable key is safe to ship. */
window.OMNISTORE = {
  "gateway": "http://localhost:8080",
  "store": "omnistore-demo",
  "publishableKey": "pb_pk_WamVtTJ3FEfGmdAw8tAh8dev6E5ufjnv_9N5VJPcxEk"
};
