"""Generate ``web/config.js`` from the keys the platform just issued.

The browser only ever gets the *publishable* key: it is safe in source control
and in a URL. The secret key is for the back office, so it is printed to stdout
and pasted into the UI at runtime (kept in localStorage, never written here).

Run after :mod:`bootstrap` has created the project.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).parent


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gateway", default="http://localhost:8080")
    parser.add_argument("--store", default="omnistore-demo", help="the store slug the storefront uses")
    parser.add_argument("--publishable", required=True)
    parser.add_argument("--out", default=str(HERE / "web" / "config.js"))
    args = parser.parse_args()

    config = {
        "gateway": args.gateway.rstrip("/"),
        "store": args.store,
        "publishableKey": args.publishable,
    }
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(
        "/* Generated by bootstrap.py — the publishable key is safe to ship. */\n"
        "window.OMNISTORE = " + json.dumps(config, indent=2) + ";\n"
    )
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
