"""Compiling an environment into a Sillo application.

The compiled application serves the environment's data plane under
``/rest/v1``: its resources, its custom routes, and the project's own Sillo
router. It is rebuilt when the environment's version changes. Its OpenAPI
document is Sillo's, so the Atlas documentation always matches what is enforced.
"""

from __future__ import annotations

import json
import logging
from typing import TYPE_CHECKING

from pydantic import ValidationError
from sillo import HttpContext, SilloApp
from sillo import json as json_response
from sillo.openapi import Atlas

from app.compiler.common import error_body
from app.compiler.resources import register_resource
from app.compiler.routes import register_route
from app.data.source import DataSourceError
from app.data.sql import SqlError
from app.execution import NotFound
from pawabase_kit.auth import ProjectUserBackend
from pawabase_kit.flows import FlowError
from pawabase_kit.principal import Principal
from pawabase_kit.transformers import TransformerError

if TYPE_CHECKING:
    from app.state import EnvironmentState

logger = logging.getLogger("pawabase.compiler")

REST_PREFIX = "/rest/v1"


def shadows_resource(path: str, resources: object) -> bool:
    """Whether *path* is ``/<resource>`` or ``/<resource>/{param}``.

    Actions such as ``/orders/{id}/pay`` are fine; only the resource's own
    collection and item paths are reserved.
    """
    segments = path.strip("/").split("/")
    if not segments or segments[0] not in resources:
        return False
    return len(segments) == 1 or (len(segments) == 2 and segments[1].startswith("{"))


def compile_environment(state: EnvironmentState) -> SilloApp:
    settings = state.platform.settings
    app = SilloApp(
        title=f"{state.project_name} API",
        version=f"{state.env_name} v{state.version}",
        description=(
            f"The **{state.env_name}** API of **{state.project_name}**, generated by Pawabase.\n\n"
            "Send your project key in the `apikey` header or use `Authorization: Bearer <token>` for signed-in sessions. "
            "Both authentication methods are fully supported. Every request also requires "
            "`?project_id=<ref>&environment=<env>` query parameters, so the gateway can scope key resolution to this "
            "project/environment."
        ),
        debug=settings.debug,
        auth=[ProjectUserBackend(settings.jwt_master_secret)],
        auth_user_model=Principal,
        docs=[Atlas(path="/docs")],
    )
    app.state["environment"] = state
    problems: list[str] = list(state.schema_problems)

    async def flow_error(ctx: HttpContext, exc: FlowError):
        status = exc.status if 400 <= exc.status < 600 else 500
        details = exc.details if isinstance(exc.details, (dict, list)) else None
        return json_response(
            error_body(
                exc.code if exc.code != "raised" else (details or {}).get("code", "error"),
                exc.message,
                details if exc.code != "raised" else None,
            ),
            status_code=status,
        )

    async def sql_error(ctx: HttpContext, exc: SqlError):
        return json_response(error_body("bad_request", str(exc)), status_code=400)

    async def not_found(ctx: HttpContext, exc: NotFound):
        return json_response(error_body("not_found", str(exc)), status_code=404)

    async def unavailable(ctx: HttpContext, exc: DataSourceError):
        return json_response(error_body("database_unavailable", str(exc)), status_code=503)

    async def invalid(ctx: HttpContext, exc: ValidationError):
        return json_response(
            error_body("invalid", "validation failed", json.loads(exc.json(include_url=False))),
            status_code=422,
        )

    async def transformer_error(ctx: HttpContext, exc: TransformerError):
        return json_response(error_body("transformer_error", str(exc)), status_code=500)

    app.add_exception_handler(FlowError, flow_error)
    app.add_exception_handler(SqlError, sql_error)
    app.add_exception_handler(NotFound, not_found)
    app.add_exception_handler(DataSourceError, unavailable)
    app.add_exception_handler(ValidationError, invalid)
    app.add_exception_handler(TransformerError, transformer_error)

    for resource in state.resources.values():
        try:
            register_resource(app, state, resource)
        except Exception as exc:
            logger.exception("resource %s could not be compiled", resource.name)
            problems.append(f"resource {resource.name}: {exc}")

    for route in state.routes:
        if shadows_resource(route.path, state.resources):
            problems.append(f"route {route.method} {route.path}: shadows a resource route")
            continue
        try:
            register_route(app, state, route)
        except Exception as exc:
            logger.exception("route %s %s could not be compiled", route.method, route.path)
            problems.append(f"route {route.method} {route.path}: {exc}")

    code = state.platform.code.get(state.project_ref)
    if code is not None and code.router is not None:
        try:
            app.mount_router(code.router)
        except Exception as exc:
            problems.append(f"routes.py: {exc}")
    app.state["problems"] = problems
    return app
