/* eslint-disable */
// Generated by pawabase-types from the openapi.json fixture.
// Do not edit by hand: regenerate when your resources change.

export interface AuthorsRow {
  id: number;
  name: string;
  created_at?: string;
  updated_at?: string;
}

export interface AuthorsInsert {
  name: string;
}

export interface AuthorsUpdate {
  name?: string | null;
}

export interface PostsRow {
  id: number;
  title: string;
  status: string;
  views: number;
  featured: boolean;
  org_id: string | null;
  author_id: number | null;
  meta: unknown;
  created_at?: string;
  updated_at?: string;
}

export interface PostsInsert {
  title: string;
  status?: string | null;
  views?: number | null;
  featured?: boolean | null;
  org_id?: string | null;
  author_id?: number | null;
  meta?: unknown;
}

export interface PostsUpdate {
  title?: string | null;
  status?: string | null;
  views?: number | null;
  featured?: boolean | null;
  org_id?: string | null;
  author_id?: number | null;
  meta?: unknown;
}

export interface TasksRow {
  id: number;
  title: string;
  created_at?: string;
  updated_at?: string;
}

export interface TasksInsert {
  title: string;
}

export interface TasksUpdate {
  title?: string | null;
}

export interface Database {
  resources: {
    authors: { Row: AuthorsRow; Insert: AuthorsInsert; Update: AuthorsUpdate };
    posts: { Row: PostsRow; Insert: PostsInsert; Update: PostsUpdate };
    tasks: { Row: TasksRow; Insert: TasksInsert; Update: TasksUpdate };
  };
}

/** A resource's row: `Row<"posts">`. */
export type Row<K extends keyof Database["resources"]> = Database["resources"][K]["Row"];
/** What a create accepts: `Insert<"posts">`. */
export type Insert<K extends keyof Database["resources"]> = Database["resources"][K]["Insert"];
/** What an update accepts: `Update<"posts">`. */
export type Update<K extends keyof Database["resources"]> = Database["resources"][K]["Update"];
