"""Resources: geography, configuration, identity, fleets and businesses."""

from helpers import F, HM, OPS, SLUG, BT, lat, lng, money, resource, ts

READ = "config_read"
WRITE = "config_write"

VEHICLE_CLASSES = ["bicycle", "motorcycle", "tricycle", "compact_car", "standard_car",
                   "premium_car", "van", "small_truck", "large_truck"]

DRIVER_STATES = ["offline", "online", "available", "receiving_offer", "reserved",
                 "to_pickup", "waiting_at_pickup", "active_trip", "active_delivery",
                 "at_stop", "paused", "completing", "temporarily_unavailable",
                 "suspended", "restricted"]

RESOURCES = [
    # ── geography ────────────────────────────────────────────────────────────
    resource("markets", "A city/region the platform operates in. Coordinates anchor distance math.", [
        F("slug", required=True, pattern=SLUG, unique=True),
        F("name", required=True, max_length=120),
        F("country", required=True, pattern=r"^[A-Z]{2}$"),
        F("currency", required=True, min_length=3, max_length=3),
        F("timezone", default="Africa/Lagos", max_length=60),
        lat("center_lat", required=True), lng("center_lng", required=True),
        F("km_per_deg_lng", "number", default=111.32, description="Longitude scale at this latitude"),
        F("active", "boolean", default=True),
    ], OPS(list_=READ, get=READ, create=WRITE, update=WRITE, delete="admin_only"), tags=["Geo"], cache_ttl=300),

    resource("zones", "Operational geography: zones, restricted and special areas, as bounding boxes "
                      "(plus an optional polygon for display).", [
        F("slug", required=True, pattern=SLUG, indexed=True),
        F("market", required=True, indexed=True, description="Market slug"),
        F("name", required=True, max_length=120),
        F("kind", required=True, enum=["operational", "restricted", "pickup_only", "dropoff_only",
                                       "premium", "airport", "high_demand", "temporary_restricted"]),
        F("min_lat", "number", required=True), F("max_lat", "number", required=True),
        F("min_lng", "number", required=True), F("max_lng", "number", required=True),
        F("polygon", "json", description="GeoJSON ring for display and future point-in-polygon"),
        F("priority", "integer", default=0, description="Higher wins when zones overlap"),
        F("active_from", "datetime"), F("active_to", "datetime"),
        F("active", "boolean", default=True),
    ], OPS(list_=READ, get=READ, create=WRITE, update=WRITE, delete="admin_only"), tags=["Geo"], cache_ttl=300),

    # ── service catalogue and pricing ────────────────────────────────────────
    resource("services", "A sellable product (Economy Ride, Express Courier, …) with its rules.", [
        F("slug", required=True, pattern=SLUG, unique=True),
        F("name", required=True, max_length=120),
        F("kind", required=True, enum=["ride", "delivery", "both"]),
        F("description", "text"),
        F("vehicle_classes", "array", items={"type": "string"}, default=["standard_car"]),
        F("min_class_rank", "integer", default=5, minimum=1, maximum=9,
            description="Eligible vehicle classes, as a rank range: bicycle 1 … large_truck 9"),
        F("max_class_rank", "integer", default=6, minimum=1, maximum=9),
        F("min_driver_rating", "number", default=0, minimum=0, maximum=5),
        F("max_distance_km", "number", default=100),
        F("max_weight_kg", "number", default=0, description="0: not a carrying service"),
        F("operating_hours", "json", description='{"start": "05:00", "end": "23:00"} — empty: always'),
        F("markets", "array", items={"type": "string"}, default=[], description="Empty: every market"),
        F("cancellation", "json", description="{free_before_assign: true, fee_after_assign_minor: 150000, "
                                              "fee_after_arrival_minor: 300000, driver_comp_minor: 100000}"),
        F("waiting", "json", description="{free_seconds: 300, per_minute_minor: 5000, max_billable_seconds: 1800}"),
        F("r1_radius_km", "number", default=2.0), F("r1_offer_seconds", "integer", default=18),
        F("r1_pool", "integer", default=5), F("r1_min_rating", "number", default=4.7),
        F("r2_radius_km", "number", default=4.0), F("r2_offer_seconds", "integer", default=20),
        F("r2_pool", "integer", default=8), F("r2_min_rating", "number", default=4.3),
        F("r3_radius_km", "number", default=7.0), F("r3_offer_seconds", "integer", default=22),
        F("r3_pool", "integer", default=12), F("r3_min_rating", "number", default=3.8),
        F("r4_radius_km", "number", default=12.0), F("r4_offer_seconds", "integer", default=25),
        F("r4_pool", "integer", default=20), F("r4_min_rating", "number", default=0.0),
        F("compensation", "json", description='{"driver_share_bps": 8000} — what the driver keeps'),
        F("platform_fee_bps", "integer", default=2000, minimum=0, maximum=5000),
        F("priority", "boolean", default=False, description="Priority dispatch for a fee"),
        F("active", "boolean", default=True),
    ], OPS(list_=READ, get=READ, create=WRITE, update=WRITE, delete="admin_only"), tags=["Catalog"], cache_ttl=120),

    resource("pricing_rules", "Price book: one row per (market, service). Amounts in minor units.", [
        F("market", required=True, indexed=True),
        F("service", required=True, indexed=True),
        money("base_minor", required=True),
        money("per_km_minor", default=0),
        money("per_minute_minor", default=0),
        money("minimum_minor", default=0),
        F("multiplier", "number", default=1.0, minimum=0, maximum=10, description="Service/vehicle multiplier"),
        F("zone_fees", "json", description='{"airport-ikeja": 50000} added when pickup or dropoff is inside'),
        money("airport_fee_minor", default=0),
        money("stop_fee_minor", default=0, description="Per added stop"),
        money("schedule_fee_minor", default=0, description="For scheduled bookings"),
        money("priority_fee_minor", default=0),
        F("weight_per_kg_minor", "integer", default=0),
        F("oversize_threshold_cm", "integer", default=0),
        money("oversize_fee_minor", default=0),
        F("tax_bps", "integer", default=750, minimum=0, maximum=5000, description="VAT/GST basis points"),
        F("surge_t1_ratio", "number", default=0, description="Demand/supply where tier 1 starts (0: off)"),
        F("surge_t1_multiplier", "number", default=1.0, minimum=1.0, maximum=5.0),
        F("surge_t2_ratio", "number", default=0),
        F("surge_t2_multiplier", "number", default=1.0, minimum=1.0, maximum=5.0),
        F("surge_t3_ratio", "number", default=0),
        F("surge_t3_multiplier", "number", default=1.0, minimum=1.0, maximum=5.0),
        F("currency", default="NGN", min_length=3, max_length=3),
        F("active", "boolean", default=True),
    ], OPS(list_=READ, get=READ, create=WRITE, update=WRITE, delete="admin_only"), tags=["Catalog"], cache_ttl=120),

    resource("zone_fees", "A fee a service charges when a pickup or dropoff lands in a zone.", [
        F("market", required=True, indexed=True),
        F("service", required=True, indexed=True),
        F("zone_slug", required=True, indexed=True),
        money("pickup_fee_minor", default=0),
        money("dropoff_fee_minor", default=0),
        F("active", "boolean", default=True),
    ], OPS(list_=READ, get=READ, create=WRITE, update=WRITE, delete="admin_only"), tags=["Catalog"], cache_ttl=120),

    resource("promotions", "Promo codes and targeted offers.", [
        F("code", required=True, unique=True, pattern=r"^[A-Z0-9_-]{3,40}$"),
        F("title", required=True, max_length=120),
        F("kind", required=True, enum=["percentage", "fixed", "free_delivery"]),
        F("value", "integer", required=True, minimum=0,
            description="Basis points for percentage, minor units for fixed"),
        money("max_discount_minor"), money("min_order_minor"),
        F("usage_limit", "integer", minimum=1), F("per_user_limit", "integer", minimum=1),
        F("usage_count", "integer", default=0, read_only=True),
        F("services", "array", items={"type": "string"}, default=[]),
        F("markets", "array", items={"type": "string"}, default=[]),
        F("zones", "array", items={"type": "string"}, default=[]),
        F("user_ids", "array", items={"type": "string"}, default=[], description="Targeted offers"),
        F("first_job_only", "boolean", default=False),
        F("starts_at", "datetime"), F("ends_at", "datetime"),
        F("active", "boolean", default=True),
    ], OPS(list_="staff_read", get="staff_read", create=WRITE, update=WRITE, delete="admin_only"),
        tags=["Marketing"]),

    resource("incentives", "Driver incentives: quests and zone/time multipliers.", [
        F("slug", required=True, pattern=SLUG, unique=True),
        F("name", required=True, max_length=120),
        F("description", "text"),
        F("kind", required=True, enum=["trip_count", "delivery_count", "zone_presence", "streak"]),
        F("window", required=True, enum=["daily", "weekly"]),
        F("target_count", "integer", default=0, minimum=0),
        F("zone", description="Zone slug for zone_presence"),
        F("hours", "json", description='{"start": "17:00", "end": "20:00"}'),
        money("bonus_minor", default=0),
        F("earnings_multiplier", "number", default=1.0, minimum=1.0, maximum=5.0),
        F("market", indexed=True),
        F("starts_at", "datetime"), F("ends_at", "datetime"),
        F("active", "boolean", default=True),
    ], OPS(list_=READ, get=READ, create=WRITE, update=WRITE, delete="admin_only"), tags=["Marketing"], cache_ttl=120),

    resource("feature_flags", "Operational feature toggles with rollout targeting.", [
        F("key", required=True, pattern=r"^[a-z][a-z0-9_.-]{1,62}$", unique=True),
        F("description", max_length=240),
        F("enabled", "boolean", default=False),
        F("rollout", "json", description="{countries: [], markets: [], zones: [], user_ids: [], "
                                         "driver_ids: [], orgs: [], percentage: 100}"),
    ], OPS(list_="staff_read", get="staff_read", create=WRITE, update=WRITE, delete="admin_only"),
        tags=["Ops"], cache_ttl=60),

    resource("ops_flags", "Live disruption switches: disable services, zones, methods, assignments.", [
        F("scope", required=True, enum=["service", "zone_pickup", "zone_delivery", "payment_method",
                                        "assignments", "vehicle_class"], indexed=True),
        F("scope_key", required=True, max_length=80, indexed=True),
        F("disabled", "boolean", default=False),
        F("reason", max_length=240),
        F("set_by", max_length=120),
        F("set_at", "datetime"),
    ], OPS(list_="staff_read", get="staff_read", create="ops_manage", update="ops_manage", delete="ops_manage"),
        tags=["Ops"]),

    # ── drivers ──────────────────────────────────────────────────────────────
    resource("driver_profiles", "A driver's operational identity and live state machine.", [
        F("user_id", required=True, unique=True, description="Akountz user id"),
        F("full_name", required=True, max_length=160),
        F("phone", required=True, max_length=32),
        F("state", required=True, enum=DRIVER_STATES, default="offline", indexed=True),
        F("onboarding_status", required=True, default="started", indexed=True,
            enum=["started", "personal_info", "identity_submitted", "vehicle_submitted",
                  "documents_submitted", "verification", "background_review",
                  "approved", "rejected", "activated"]),
        F("rejection_reason", max_length=500),
        F("market", required=True, indexed=True),
        F("fleet_id", pattern=SLUG, indexed=True, description="Fleet org slug, when fleet-employed"),
        F("license_number", required=True, max_length=60),
        F("license_expiry", "date", required=True),
        F("date_of_birth", "date"),
        F("home_address", "json"),
        F("payout_account", "json", description="{provider, account_name, account_number, bank_code}"),
        F("current_vehicle_id", "integer"),
        F("vehicle_class", max_length=40, description="Denormalized from the current vehicle"),
        F("vehicle_class_rank", "integer", default=0, minimum=0, maximum=9,
            description="Denormalized class rank, for matching SQL"),
        F("vehicle_weight_kg", "number", default=0, description="Denormalized capacity, for delivery matching"),
        F("vehicle_plate", max_length=20),
        F("vehicle_description", max_length=160),
        F("last_lat", "number"), F("last_lng", "number"),
        F("last_heading", "number"), F("last_speed_kph", "number"),
        ts("last_location_ts", description="Device clock of the newest accepted ping — out-of-order guard"),
        F("location_stale", "boolean", default=True),
        ts("online_since_ts"),
        F("rating_avg", "number", default=0, minimum=0, maximum=5),
        F("rating_count", "integer", default=0),
        F("trips_completed", "integer", default=0),
        F("deliveries_completed", "integer", default=0),
        F("offers_received", "integer", default=0),
        F("offers_accepted", "integer", default=0),
        F("jobs_cancelled", "integer", default=0),
        F("acceptance_rate", "number", default=0),
        F("cancellation_rate", "number", default=0),
        F("completion_rate", "number", default=0),
        F("on_time_rate", "number", default=0),
        F("restricted_reason", max_length=240),
        ts("restricted_at"),
        F("strike_count", "integer", default=0),
    ], OPS(list_="staff_read", get="driver_self", create=False, update="onboarding_manage", delete="admin_only"),
        tags=["Drivers"], realtime=True),

    resource("vehicles", "Vehicles a driver or fleet operates, with compliance dates.", [
        F("driver_user_id", required=True, indexed=True),
        F("fleet_id", pattern=SLUG, indexed=True),
        F("class", required=True, enum=VEHICLE_CLASSES, indexed=True),
        F("make", required=True, max_length=60), F("model", required=True, max_length=60),
        F("year", "integer", minimum=1990, maximum=2100), F("color", max_length=40),
        F("plate", required=True, indexed=True, max_length=20),
        F("passenger_capacity", "integer", default=1, minimum=0, maximum=60),
        F("weight_capacity_kg", "number", default=0, minimum=0, maximum=40000),
        F("cargo_length_cm", "number", minimum=0), F("cargo_width_cm", "number", minimum=0),
        F("cargo_height_cm", "number", minimum=0),
        F("ownership", enum=["owned", "leased", "fleet"], default="owned"),
        F("registration_expiry", "date"), F("insurance_expiry", "date"),
        F("inspection_at", "date"), F("inspection_expiry", "date"),
        F("verified", "boolean", default=False),
        F("status", enum=["active", "maintenance", "retired", "suspended"], default="active"),
    ], OPS(list_="driver_self", get="driver_self", create="driver_role", update="driver_self", delete="admin_only"),
        tags=["Drivers"]),

    resource("documents", "Compliance documents for drivers and vehicles, with a verification lifecycle.", [
        F("subject_type", required=True, enum=["driver", "vehicle"], indexed=True),
        F("subject_id", required=True, indexed=True,
            description="Driver user_id, or vehicle id as a string"),
        F("kind", required=True, enum=["license", "identity", "insurance", "registration",
                                       "inspection", "background_check", "photo"]),
        F("status", required=True, indexed=True, default="pending",
            enum=["pending", "processing", "needs_info", "approved", "rejected", "expired"]),
        F("file_key", required=True, max_length=300, description="Object key in driver-documents / vehicle-documents"),
        F("expires_at", "date"),
        F("submitted_by", required=True, max_length=120),
        F("reviewed_by", max_length=120),
        F("reviewed_at", "datetime"),
        F("review_notes", "text"),
        ts("renewal_reminded_ts"),
        F("renewal_reminder_count", "integer", default=0),
    ], OPS(list_="staff_read", get="staff_read", create=False, update="onboarding_manage", delete="admin_only"),
        relations=[], tags=["Drivers"]),

    # ── organizations (fleets and businesses are Akountz orgs; these are the platform-side records) ──
    resource("fleets", "Platform record of a fleet organization.", [
        F("fleet_id", required=True, pattern=SLUG, unique=True, description="The organization slug"),
        F("name", required=True, max_length=120),
        F("market", required=True, indexed=True),
        F("contact_email", "email", required=True),
        F("commission_bps", "integer", default=1000, minimum=0, maximum=4000),
        F("payout_schedule", enum=["daily", "weekly"], default="weekly"),
        F("active", "boolean", default=True),
    ], OPS(list_="fleet_staff", get="fleet_staff", create=False, update="fleet_managers", delete="admin_only"),
        tags=["Fleets"], cache_ttl=120),

    resource("businesses", "Platform record of a business customer organization.", [
        F("org_id", required=True, pattern=SLUG, unique=True, description="The organization slug"),
        F("name", required=True, max_length=120),
        F("billing_email", "email", required=True),
        F("market", required=True, indexed=True),
        money("monthly_limit_minor"),
        money("approval_threshold_minor", default=0),
        money("month_to_date_minor", default=0, read_only=True, description="Spend this calendar month"),
        F("status", enum=["active", "suspended", "closed"], default="active"),
    ], OPS(list_="business_staff", get="business_staff", create=False, update="business_managers",
           delete="admin_only"), tags=["Business"], cache_ttl=120),

    resource("org_policies", "What a business allows its employees to book, and when approvals kick in.", [
        F("org_id", required=True, pattern=SLUG, unique=True),
        money("max_ride_minor"),
        F("allowed_services", "array", items={"type": "string"}, default=[]),
        F("operating_hours", "json"),
        F("allowed_pickup_zones", "array", items={"type": "string"}, default=[]),
        F("allowed_dropoff_zones", "array", items={"type": "string"}, default=[]),
        money("monthly_limit_minor"),
        money("per_employee_limit_minor"),
        money("approval_threshold_minor", default=0),
    ], OPS(list_="business_staff", get="business_staff", create="business_managers",
           update="business_managers", delete="business_managers"), tags=["Business"]),

    resource("org_automations", "Event-driven automations a business configures for its own operations.", [
        F("org_id", required=True, pattern=SLUG, indexed=True),
        F("name", required=True, max_length=120),
        F("event", required=True, max_length=128, description="Event pattern, e.g. delivery.delivered"),
        F("condition", "json", description="Optional policy condition over $event"),
        F("action", required=True, enum=["notify_webhook", "notify_email", "require_approval", "emit_event"]),
        F("action_config", "json", description="{url} | {to} | {threshold_minor} | {event}"),
        F("enabled", "boolean", default=True),
    ], OPS(list_="business_staff", get="business_staff", create="business_managers",
           update="business_managers", delete="business_managers"), tags=["Business"]),

    # ── customer data ────────────────────────────────────────────────────────
    resource("saved_addresses", "A customer's saved places.", [
        F("user_id", required=True, indexed=True),
        F("label", required=True, max_length=40),
        F("address", "json", required=True),
        F("is_default", "boolean", default=False),
    ], OPS(list_="customer_self", get="customer_self", create="customer_create",
           update="customer_self", delete="customer_self"), owner="user_id", tags=["Customers"]),

    resource("recipients", "Saved recipients of a sender or a business.", [
        F("user_id", indexed=True, description="The sender who saved this recipient"),
        F("org_id", pattern=SLUG, indexed=True, description="The business that owns this recipient"),
        F("name", required=True, max_length=120),
        F("phone", required=True, max_length=32),
        F("email", "email"),
        F("address", "json", required=True),
        F("delivery_pin", max_length=12),
        F("notes", "text"),
    ], OPS(list_="recipient_owner", get="recipient_owner", create="customer_create",
           update="recipient_owner", delete="recipient_owner"), tags=["Customers"]),
]
