"""Resources: payments, wallets, payouts, promotions usage, support, risk, comms."""

from helpers import F, OPS, BT, money, resource, ts

FINANCE = "finance_manage"
STAFF = "staff_read"

RESOURCES = [
    # ── payment instruments ──────────────────────────────────────────────────
    resource("payment_methods", "A customer's or business's way to pay.", [
        F("user_id", required=True, indexed=True),
        F("kind", required=True, enum=["card", "wallet", "business", "cash"], default="card"),
        F("label", required=True, max_length=60),
        F("brand", max_length=20),
        F("last4", max_length=4),
        F("expiry", max_length=5),
        F("provider_token", max_length=120, description="Gateway token — never leaves the server"),
        F("is_default", "boolean", default=False),
        F("status", enum=["active", "restricted", "removed"], default="active"),
    ], OPS(list_="customer_self", get="customer_self", create="customer_create",
           update="customer_self", delete="customer_self"),
        owner="user_id", tags=["Payments"], transformer="customer_payment"),

    # ── wallets and ledger ───────────────────────────────────────────────────
    resource("wallets", "A money balance for a driver, customer, fleet or business.", [
        F("owner_type", required=True, enum=["driver", "customer", "fleet", "business"], indexed=True),
        F("owner_id", required=True, indexed=True, description="user id or org slug"),
        F("balance_minor", "integer", default=0),
        F("held_minor", "integer", default=0, description="Held by risk or pending payout"),
        F("currency", min_length=3, max_length=3, default="NGN"),
        F("status", enum=["active", "frozen"], default="active"),
    ], OPS(list_="finance_manage", get="finance_manage", create=False, update=False, delete=False),
        tags=["Payments"]),

    resource("wallet_entries", "The ledger: every movement on a wallet, idempotent by key.", [
        F("wallet_id", "integer", required=True, indexed=True),
        F("owner_id", required=True, indexed=True, description="Denormalized for policy pushdown"),
        F("kind", required=True, enum=["earning", "bonus", "adjustment", "withdrawal", "payout",
                                       "reversal", "hold", "release", "topup", "fare_charge"]),
        F("amount_minor", "integer", required=True, description="Signed: credit positive, debit negative"),
        F("balance_after_minor", "integer", required=True),
        F("ref_type", max_length=40), F("ref_id", max_length=80),
        F("note", max_length=240),
        F("idempotency_key", max_length=96, unique=True),
    ], OPS(list_="finance_manage", get="finance_manage", create=False, update=False, delete=False),
        relations=[BT("wallet", "wallets", "wallet_id")], tags=["Payments"]),

    # ── payments ─────────────────────────────────────────────────────────────
    resource("payments", "A charge for a job, with its own lifecycle independent of the job.", [
        F("subject_type", required=True, enum=["ride", "delivery"], indexed=True),
        F("subject_id", "integer", required=True, indexed=True),
        F("user_id", required=True, indexed=True),
        F("org_id", pattern="^[a-z0-9][a-z0-9-]{1,62}$", indexed=True),
        F("method", required=True, enum=["card", "wallet", "cash", "business", "promo_balance"]),
        F("method_id", "integer"),
        money("amount_minor", required=True),
        F("currency", min_length=3, max_length=3, default="NGN"),
        F("status", required=True, default="requires_authorization", indexed=True,
            enum=["requires_authorization", "authorized", "capture_pending", "captured",
                  "failed", "auth_failed", "refunded", "partially_refunded", "disputed", "cancelled"]),
        F("provider", max_length=40, default="gateway"),
        F("provider_ref", max_length=120, indexed=True),
        F("idempotency_key", max_length=96, unique=True),
        ts("authorized_ts"), ts("captured_ts"),
        F("failure_code", max_length=60),
        F("failure_detail", max_length=500),
        F("retry_count", "integer", default=0),
        ts("next_retry_ts"),
        money("refunded_minor", default=0),
        F("risk_flags", "json", default=[]),
        F("provider_payload", "json"),
    ], OPS(list_=STAFF, get=STAFF, create=False, update=False, delete=False),
        tags=["Payments"], realtime=True),

    resource("payment_events", "Every inbound payment-provider event, deduplicated by provider id.", [
        F("provider", required=True, max_length=40),
        F("provider_event_id", required=True, unique=True, max_length=120),
        F("payment_id", "integer", indexed=True),
        F("kind", required=True, max_length=60, description="charge.success, charge.failed, refund.processed, …"),
        F("payload", "json"),
        F("processed", "boolean", default=False),
        ts("processed_ts"),
        F("note", max_length=240, description="late_ignored, applied, replayed, …"),
    ], OPS(list_=STAFF, get=STAFF, create=False, update=False, delete=False),
        tags=["Payments"]),

    resource("refunds", "A repayment, moving through approval and provider confirmation.", [
        F("payment_id", "integer", required=True, indexed=True),
        F("subject_type", required=True, max_length=20),
        F("subject_id", "integer", required=True),
        money("amount_minor", required=True),
        F("reason", required=True, max_length=240),
        F("status", required=True, default="requested", indexed=True,
            enum=["requested", "approved", "processing", "completed", "failed", "rejected"]),
        F("requested_by", required=True, max_length=120),
        F("approved_by", max_length=120),
        F("provider_ref", max_length=120),
        F("failure", max_length=240),
        F("idempotency_key", max_length=96, unique=True),
        ts("requested_ts", required=True), ts("completed_ts"),
    ], OPS(list_=STAFF, get=STAFF, create=False, update=False, delete=False),
        tags=["Payments"]),

    # ── driver money ─────────────────────────────────────────────────────────
    resource("earnings", "What a driver earned on one job, fully itemized.", [
        F("driver_user_id", required=True, indexed=True),
        F("job_type", required=True, enum=["ride", "delivery", "route"]),
        F("job_id", "integer", required=True, indexed=True),
        money("gross_minor", required=True),
        money("platform_fee_minor", default=0),
        F("fleet_id", max_length=80),
        money("fleet_fee_minor", default=0),
        money("tips_minor", default=0),
        money("bonus_minor", default=0),
        money("tax_minor", default=0),
        money("net_minor", required=True),
        F("currency", min_length=3, max_length=3, default="NGN"),
        F("adjustments", "json", default=[]),
        F("adjustment_notes", max_length=500),
        F("paid_out", "boolean", default=False),
        F("payout_id", "integer"),
    ], OPS(list_=STAFF, get=STAFF, create=False, update=False, delete=False),
        tags=["Earnings"], transformer="earnings_view"),

    resource("payouts", "A transfer of earnings to a driver or fleet, with recovery paths.", [
        F("owner_type", required=True, enum=["driver", "fleet"], indexed=True),
        F("owner_id", required=True, indexed=True),
        money("amount_minor", required=True),
        F("currency", min_length=3, max_length=3, default="NGN"),
        F("status", required=True, default="pending", indexed=True,
            enum=["pending", "processing", "paid", "failed", "reversed"]),
        F("period_start", "date"), F("period_end", "date"),
        F("entries_count", "integer", default=0),
        F("provider", max_length=40),
        F("provider_ref", max_length=120),
        F("failure", max_length=240),
        F("attempt_count", "integer", default=0),
        ts("next_retry_ts"),
        F("idempotency_key", max_length=96, unique=True),
        F("reversed_reason", max_length=240),
        ts("paid_ts"),
    ], OPS(list_="finance_manage", get="finance_manage", create=False, update=False, delete=False),
        tags=["Earnings"], realtime=True),

    # ── promotions and incentives ────────────────────────────────────────────
    resource("promo_redemptions", "Who used which promotion on which job.", [
        F("promo_code", required=True, indexed=True, max_length=40),
        F("user_id", required=True, indexed=True),
        F("subject_type", required=True, max_length=20),
        F("subject_id", "integer", required=True),
        money("discount_minor", required=True),
    ], OPS(list_="customer_self", get="customer_self", create=False, update=False, delete=False),
        tags=["Marketing"]),

    resource("incentive_progress", "A driver's live progress toward one incentive window.", [
        F("incentive_slug", required=True, indexed=True),
        F("driver_user_id", required=True, indexed=True),
        F("window_key", required=True, max_length=20, description="2026-09-28 or 2026-W40"),
        F("progress_count", "integer", default=0),
        F("target_count", "integer", default=0),
        F("achieved", "boolean", default=False),
        ts("achieved_ts"),
        money("bonus_minor", default=0),
        F("paid", "boolean", default=False),
    ], OPS(list_="staff_read", get="staff_read", create=False, update=False, delete=False),
        tags=["Earnings"], realtime=True),

    # ── support ──────────────────────────────────────────────────────────────
    resource("support_tickets", "A support case with SLA tracking.", [
        F("user_id", required=True, indexed=True),
        F("category", required=True, max_length=40, indexed=True),
        F("subject", required=True, max_length=200),
        F("status", required=True, default="open", indexed=True,
            enum=["open", "pending_customer", "pending_support", "escalated", "resolved", "closed"]),
        F("priority", required=True, default="normal", enum=["low", "normal", "high", "urgent"]),
        F("job_type", max_length=20), F("job_id", "integer"),
        F("assigned_to", max_length=120),
        ts("sla_due_ts"),
        F("messages_count", "integer", default=0),
        ts("last_message_ts"),
        ts("resolved_ts"),
        F("internal_notes", "text"),
    ], OPS(list_="ticket_party", get="ticket_party", create="customer_create", update="ops_manage",
           delete="admin_only"),
        relations=[], tags=["Support"], transformer="support_ticket_view", realtime=True),

    resource("ticket_messages", "The conversation on a ticket.", [
        F("ticket_id", "integer", required=True, indexed=True),
        F("sender_id", required=True, max_length=120),
        F("from_staff", "boolean", default=False),
        F("body", required=True, max_length=5000),
        F("attachments", "array", items={"type": "string"}, default=[]),
    ], OPS(list_="ticket_party", get="ticket_party", create=False, update=False, delete=False),
        relations=[BT("ticket", "support_tickets", "ticket_id")], tags=["Support"]),

    resource("lost_item_cases", "A lost-property case; can stay open for days.", [
        F("ride_id", "integer", required=True, indexed=True),
        F("user_id", required=True, indexed=True),
        F("driver_user_id", required=True, indexed=True),
        F("description", required=True, max_length=2000),
        F("contact_phone", max_length=32),
        F("status", required=True, default="reported", indexed=True,
            enum=["reported", "driver_contacted", "awaiting_response", "found", "not_found",
                  "return_arranged", "completed", "closed"]),
        ts("driver_contacted_ts"), ts("driver_responded_ts"),
        F("found_item", "boolean"),
        F("return_details", "json"),
        F("reminders_sent", "integer", default=0),
        ts("last_reminder_ts"),
        ts("resolved_ts"),
    ], OPS(list_="ticket_party", get="ticket_party", create=False, update="ops_manage", delete="admin_only"),
        tags=["Support"]),

    resource("incidents", "A safety or operational incident on an active job.", [
        F("job_type", required=True, enum=["ride", "delivery"], indexed=True),
        F("job_id", "integer", required=True, indexed=True),
        F("reporter_id", required=True, max_length=120),
        F("reporter_role", required=True, max_length=40),
        F("kind", required=True, max_length=40),
        F("severity", required=True, enum=["low", "medium", "high", "critical"], indexed=True),
        F("description", required=True, max_length=5000),
        F("evidence_keys", "array", items={"type": "string"}, default=[]),
        F("status", required=True, default="reported", indexed=True,
            enum=["reported", "acknowledged", "investigating", "resolved", "closed"]),
        F("acknowledged_by", max_length=120),
        ts("acknowledged_ts"),
        F("escalated", "boolean", default=False),
        F("assigned_to", max_length=120),
        ts("due_ts"),
        F("resolution", "text"),
    ], OPS(list_="staff_read", get="staff_read", create=False, update="ops_manage", delete="admin_only"),
        tags=["Support"], realtime=True),

    resource("ratings", "A rating between the parties of a completed job.", [
        F("job_type", required=True, enum=["ride", "delivery"], indexed=True),
        F("job_id", "integer", required=True, indexed=True),
        F("rater_id", required=True, max_length=120),
        F("ratee_id", required=True, max_length=120, indexed=True),
        F("direction", required=True, enum=["customer_to_driver", "driver_to_customer", "business_to_driver"]),
        F("score", "integer", required=True, minimum=1, maximum=5),
        F("categories", "json"),
        F("comment", max_length=2000),
    ], OPS(list_="customer_self", get="customer_self", create=False, update=False, delete=False),
        tags=["Support"]),

    # ── risk ─────────────────────────────────────────────────────────────────
    resource("risk_cases", "A fraud/risk investigation with its actions.", [
        F("subject_type", required=True, enum=["user", "driver", "payment", "org"], indexed=True),
        F("subject_id", required=True, max_length=120, indexed=True),
        F("signals", "array", items={"type": "string"}, default=[]),
        F("score", "integer", default=0, minimum=0, maximum=100),
        F("status", required=True, default="open", indexed=True,
            enum=["open", "reviewing", "actioned", "cleared", "escalated"]),
        F("assignee", max_length=120),
        F("resolution", "text"),
        F("opened_via", max_length=80),
        ts("due_ts"),
    ], OPS(list_="risk_manage", get="risk_manage", create=False, update="risk_manage", delete="admin_only"),
        tags=["Risk"]),

    resource("risk_actions", "An audited restriction applied to an account.", [
        F("case_id", "integer", required=True, indexed=True),
        F("subject_type", required=True, max_length=20),
        F("subject_id", required=True, max_length=120, indexed=True),
        F("action", required=True, enum=["flag", "require_verification", "hold_payout",
                                         "restrict_payment", "restrict_promotions", "suspend",
                                         "escalate", "clear"]),
        F("reason", required=True, max_length=500),
        F("actor_id", required=True, max_length=120),
        F("active", "boolean", default=True),
        F("reversed_by", max_length=120),
        ts("reversed_ts"),
    ], OPS(list_="risk_manage", get="risk_manage", create=False, update=False, delete=False),
        relations=[BT("case", "risk_cases", "case_id")], tags=["Risk"]),

    # ── notifications and webhooks ───────────────────────────────────────────
    resource("notifications", "A user-facing notification; fanout delivers it over channels and mail.", [
        F("user_id", required=True, indexed=True),
        F("kind", required=True, max_length=60, indexed=True),
        F("title", required=True, max_length=160),
        F("body", max_length=500),
        F("link", max_length=300),
        F("channel", default="app", max_length=20),
        F("read_at", "datetime"),
        F("delivered_via", "json", default=[]),
    ], OPS(list_="customer_self", get="customer_self", create=False, update="customer_self", delete=False),
        tags=["Comms"], realtime=True),

    resource("business_webhooks", "A business's webhook endpoint with health tracking.", [
        F("org_id", required=True, pattern="^[a-z0-9][a-z0-9-]{1,62}$", indexed=True),
        F("url", "url", required=True),
        F("events", "array", items={"type": "string"}, default=["delivery.*"]),
        F("description", max_length=240),
        F("status", enum=["active", "paused", "failing"], default="active"),
        F("fail_streak", "integer", default=0),
        ts("last_success_ts"), ts("last_failure_ts"),
        F("created_by", max_length=120),
    ], OPS(list_="business_managers", get="business_managers", create="business_managers",
           update="business_managers", delete="business_managers"), tags=["Webhooks"]),

    resource("webhook_deliveries", "One event delivery to one business endpoint, retryable and observable.", [
        F("endpoint_id", "integer", required=True, indexed=True),
        F("org_id", required=True, max_length=80, indexed=True),
        F("event", required=True, max_length=80),
        F("event_id", required=True, max_length=80, indexed=True, description="Platform event id (dedupe key)"),
        F("payload", "json"),
        F("status", required=True, default="pending", indexed=True,
            enum=["pending", "delivering", "delivered", "failed", "exhausted"]),
        F("attempts", "integer", default=0),
        ts("next_attempt_ts"),
        F("last_status_code", "integer"),
        F("last_error", max_length=300),
        F("duration_ms", "integer"),
        ts("delivered_ts"),
    ], OPS(list_="business_staff", get="business_staff", create=False, update=False, delete=False),
        relations=[BT("endpoint", "business_webhooks", "endpoint_id")], tags=["Webhooks"]),

    # ── live telemetry and rollups ───────────────────────────────────────────
    resource("location_pings", "Driver location history (support, disputes, ops replay).", [
        F("driver_user_id", required=True, indexed=True),
        F("lat", "number", required=True), F("lng", "number", required=True),
        F("heading", "number"), F("speed_kph", "number"), F("accuracy_m", "number"),
        ts("recorded_ts", required=True, description="Device clock — the ordering key"),
        ts("received_ts", required=True),
        F("state", max_length=40),
        F("job_type", max_length=20), F("job_id", "integer"),
    ], OPS(list_=STAFF, get=STAFF, create=False, update=False, delete=False),
        tags=["Ops"], events=False),

    resource("daily_stats", "Per-market, per-service daily rollups for dashboards.", [
        F("day", "date", required=True, indexed=True),
        F("market", required=True, indexed=True),
        F("service", required=True, indexed=True),
        F("requests", "integer", default=0),
        F("completed", "integer", default=0),
        F("cancelled", "integer", default=0),
        F("failed", "integer", default=0),
        money("gross_minor", default=0),
        money("avg_fare_minor", default=0),
        F("avg_pickup_min", "number", default=0),
        F("avg_delivery_min", "number", default=0),
        F("active_drivers", "integer", default=0),
        F("assignment_success_rate", "number", default=0),
        F("avg_assignment_seconds", "number", default=0),
        F("payment_failures", "integer", default=0),
        F("refunds_count", "integer", default=0),
        F("webhook_failures", "integer", default=0),
    ], OPS(list_=STAFF, get=STAFF, create=False, update=False, delete=False),
        tags=["Analytics"], cache_ttl=300),
]
