"""Resources: rides, deliveries, matching machinery, routes, batches, approvals, chat.

State machines live on these rows. Writes that change state happen only inside
flows (REST create/update/delete are disabled for job resources), so no client
can force an invalid transition — the flows check the current state, arbitrate
races with claim rows, and append timeline entries for every move.
"""

from helpers import F, HM, OPS, BT, lat, lng, money, resource, ts

RIDE_STATES = ["requested", "pending_approval", "scheduled", "searching", "driver_assigned",
               "driver_en_route", "driver_arrived", "waiting_for_customer", "in_progress",
               "at_stop", "completed", "cancelled", "failed", "disputed", "unserviceable"]

DELIVERY_STATES = ["created", "pending_approval", "scheduled", "awaiting_dispatch",
                   "searching_driver", "driver_assigned", "driver_to_pickup", "driver_at_pickup",
                   "package_collected", "in_transit", "at_destination", "delivery_attempted",
                   "delivered", "recipient_unavailable", "delivery_failed", "return_required",
                   "returning_to_sender", "returned", "cancelled", "disputed"]

JOB_PARTY = "job_party"
STAFF = "staff_read"

RESOURCES = [
    # ── pricing handoff ──────────────────────────────────────────────────────
    resource("estimates", "A priced quote, short-lived, referenced when the customer confirms.", [
        F("user_id", required=True, indexed=True),
        F("kind", required=True, enum=["ride", "delivery"]),
        F("service", required=True),
        F("market", required=True),
        F("pickup", "json", required=True),
        F("dropoff", "json"),
        F("stops", "json", default=[]),
        F("distance_km", "number", default=0),
        F("duration_min", "number", default=0),
        F("surge", "number", default=1.0),
        F("breakdown", "json", description="Line items: base, distance, time, fees, tax, discounts"),
        money("total_minor", required=True),
        F("currency", min_length=3, max_length=3),
        F("promo_code", max_length=40),
        money("discount_minor", default=0),
        ts("expires_ts", required=True),
    ], OPS(list_="customer_self", get="customer_self", create=False, update=False, delete=False),
        tags=["Pricing"]),

    # ── rides ────────────────────────────────────────────────────────────────
    resource("ride_requests", "A passenger trip: a long-running process with a full state machine.", [
        F("user_id", required=True, indexed=True),
        F("org_id", pattern="^[a-z0-9][a-z0-9-]{1,62}$", indexed=True,
            description="Billed business org, when booked on a business account"),
        F("service", required=True),
        F("market", required=True, indexed=True),
        F("status", required=True, enum=RIDE_STATES, default="requested", indexed=True),
        F("pickup", "json", required=True),
        F("dropoff", "json", required=True),
        F("stops", "json", default=[], description="Snapshot of planned stops at booking"),
        F("passengers", "integer", default=1),
        F("accessibility", "array", items={"type": "string"}, default=[]),
        F("pickup_notes", "text"),
        F("payment_method", required=True, enum=["card", "wallet", "cash", "business", "promo_balance"]),
        F("payment_method_id", "integer"),
        F("promo_code", max_length=40),
        F("estimate_id", "integer"),
        F("estimate_minor", default=0, description="The price the customer saw"),
        F("estimate_snapshot", "json", description="The estimate's breakdown at booking time"),
        F("surge", "number", default=1.0),
        F("distance_km", "number", default=0),
        F("duration_min", "number", default=0),
        money("final_fare_minor"),
        F("fare_adjustments", "json", default=[], description="Every post-booking price change, with reasons"),
        F("currency", min_length=3, max_length=3),
        F("driver_id", "integer", indexed=True, description="driver_profiles id"),
        F("driver_user_id", indexed=True),
        ts("assigned_ts"),
        F("matching_round", "integer", default=0),
        ts("matching_started_ts"),
        F("scheduled_at", "datetime"),
        ts("dispatch_ts", description="When a scheduled ride should enter matching"),
        F("idempotency_key", max_length=64, indexed=True),
        F("cancellation", "json", description="{by, reason, fee_minor, driver_comp_minor, ts}"),
        F("driver_eta_min", "integer"),
        ts("pickup_arrived_ts"),
        ts("wait_billable_from_ts"),
        money("wait_charged_minor", default=0),
        ts("started_ts"), ts("completed_ts"),
        F("share_token", max_length=64, indexed=True, description="Public tracking link token"),
        F("risk_score", "integer", default=0),
        F("risk_flags", "json", default=[]),
        F("approval_id", "integer"),
        F("created_via", default="app", max_length=40),
    ], OPS(list_="job_party", get="job_party", create=False, update=False, delete=False),
        relations=[HM("stop_rows", "ride_stops", "ride_id"), HM("timeline", "timeline_events", "subject_id")],
        tags=["Rides"], realtime=True),

    resource("ride_stops", "Stops of a multi-stop ride, each with its own mini-lifecycle.", [
        F("ride_id", "integer", required=True, indexed=True),
        F("user_id", required=True, indexed=True, description="Denormalized customer, for policy pushdown"),
        F("driver_user_id", indexed=True, description="Denormalized when assigned"),
        F("sequence", "integer", required=True, minimum=1),
        F("address", "json", required=True),
        F("instructions", "text"),
        F("contact_name", max_length=120),
        F("contact_phone", max_length=32),
        F("status", required=True, default="pending",
            enum=["pending", "arrived", "waiting", "completed", "skipped"]),
        ts("arrived_ts"), F("wait_seconds", "integer", default=0), ts("completed_ts"),
        money("extra_charge_minor", default=0),
    ], OPS(list_=JOB_PARTY, get=JOB_PARTY, create=False, update=False, delete=False),
        relations=[BT("ride", "ride_requests", "ride_id")], tags=["Rides"]),

    # ── matching ─────────────────────────────────────────────────────────────
    resource("offers", "A job opportunity offered to one driver in one matching round.", [
        F("request_type", required=True, enum=["ride", "delivery"], indexed=True),
        F("request_id", "integer", required=True, indexed=True),
        F("round", "integer", required=True),
        F("driver_user_id", required=True, indexed=True),
        F("driver_id", "integer", required=True),
        F("state", required=True, default="pending", indexed=True,
            enum=["pending", "accepted", "rejected", "expired", "superseded", "cancelled"]),
        F("score", "number", default=0),
        F("eta_min", "integer"),
        F("distance_km", "number"),
        ts("offered_ts", required=True),
        ts("expires_ts", required=True, indexed=True),
        ts("responded_ts"),
    ], OPS(list_="staff_read", get="staff_read", create=False, update=False, delete=False),
        tags=["Matching"]),

    resource("assignment_claims", "Race arbiter: the unique row that decides who wins a request.", [
        F("request_type", required=True, enum=["ride", "delivery"]),
        F("request_id", "integer", required=True, unique=True),
        F("winner", required=True, enum=["driver", "cancel", "reassign", "expire"]),
        F("winner_id", max_length=120),
        ts("created_ts", required=True),
    ], OPS(list_="staff_read", get="staff_read", create=False, update=False, delete=False),
        tags=["Matching"], events=False),

    resource("assignments", "Every driver assignment a request has had — the full history.", [
        F("request_type", required=True, enum=["ride", "delivery"], indexed=True),
        F("request_id", "integer", required=True, indexed=True),
        F("driver_user_id", required=True, indexed=True),
        F("driver_id", "integer", required=True),
        F("round", "integer", default=1),
        F("state", required=True, default="active",
            enum=["active", "released", "completed", "cancelled"]),
        ts("assigned_ts", required=True),
        ts("released_ts"),
        F("release_reason", max_length=240),
        F("previous_assignment_id", "integer"),
    ], OPS(list_="staff_read", get="staff_read", create=False, update=False, delete=False),
        tags=["Matching"]),

    resource("matching_rounds", "One observable matching round against a request.", [
        F("request_type", required=True, enum=["ride", "delivery"], indexed=True),
        F("request_id", "integer", required=True, indexed=True),
        F("round", "integer", required=True),
        F("strategy", required=True, max_length=60),
        F("radius_km", "number", default=0),
        F("candidates", "integer", default=0),
        F("offered", "integer", default=0),
        F("accepted_driver", max_length=120),
        ts("started_ts", required=True),
        ts("closed_ts"),
        F("outcome", required=True, default="open", enum=["open", "accepted", "exhausted", "cancelled"]),
    ], OPS(list_="staff_read", get="staff_read", create=False, update=False, delete=False),
        tags=["Matching"]),

    # ── the universal timeline ───────────────────────────────────────────────
    resource("timeline_events", "Append-only business history for every ride, delivery, payment, "
                                "application and case.", [
        F("subject_type", required=True, max_length=40,
            description="ride | delivery | payment | payout | application | ticket | incident | lost_item | batch | route"),
        F("subject_id", required=True, max_length=80, indexed=True),
        F("kind", required=True, max_length=60, description="matching.offer_sent, trip.started, …"),
        F("summary", required=True, max_length=300),
        F("actor_id", max_length=120, description="user id, 'system', 'scheduler', 'hook:<slug>'"),
        F("data", "json"),
    ], OPS(list_=STAFF, get=STAFF, create=False, update=False, delete=False),
        tags=["History"]),

    # ── deliveries ───────────────────────────────────────────────────────────
    resource("delivery_requests", "A package journey from sender to recipient, with failure and "
                                  "return paths.", [
        F("user_id", required=True, indexed=True, description="The sender's user id"),
        F("org_id", pattern="^[a-z0-9][a-z0-9-]{1,62}$", indexed=True),
        F("external_ref", max_length=80, indexed=True),
        F("service", required=True),
        F("market", required=True, indexed=True),
        F("status", required=True, enum=DELIVERY_STATES, default="created", indexed=True),
        F("sender", "json", required=True),
        F("recipient", "json", required=True, description="Includes delivery_pin when required"),
        F("pickup", "json", required=True),
        F("dropoff", "json", required=True),
        F("packages_count", "integer", default=1),
        F("total_weight_kg", "number", default=0),
        money("declared_value_minor", default=0),
        F("pickup_instructions", "text"),
        F("delivery_instructions", "text"),
        F("pickup_window_start", "datetime"), F("pickup_window_end", "datetime"),
        F("delivery_window_start", "datetime"), F("delivery_window_end", "datetime"),
        F("proof_required", "array", items={"type": "string"}, default=["photo"]),
        F("scheduled_at", "datetime"),
        ts("dispatch_ts"),
        F("priority", "boolean", default=False),
        F("payment_method", required=True, enum=["card", "wallet", "cash", "business", "promo_balance"]),
        F("payment_method_id", "integer"),
        F("promo_code", max_length=40),
        F("estimate_id", "integer"),
        money("estimate_minor", default=0),
        F("estimate_snapshot", "json"),
        F("surge", "number", default=1.0),
        F("distance_km", "number", default=0),
        money("final_price_minor"),
        F("price_adjustments", "json", default=[]),
        F("currency", min_length=3, max_length=3),
        F("driver_id", "integer", indexed=True),
        F("driver_user_id", indexed=True),
        ts("assigned_ts"),
        F("matching_round", "integer", default=0),
        F("attempt_count", "integer", default=0),
        ts("next_attempt_ts"),
        F("collected_ts", "integer"), ts("delivered_ts"),
        F("proof", "json", description="What the driver collected at the door"),
        F("batch_id", "integer", indexed=True),
        F("route_id", "integer", indexed=True),
        F("approval_id", "integer"),
        F("idempotency_key", max_length=64, indexed=True),
        F("cancellation", "json"),
        F("share_token", max_length=64, indexed=True),
        F("risk_score", "integer", default=0),
        F("risk_flags", "json", default=[]),
        F("internal_notes", "text"),
        F("created_via", default="app", max_length=40),
    ], OPS(list_=JOB_PARTY, get=JOB_PARTY, create=False, update=False, delete=False),
        relations=[HM("packages", "packages", "delivery_id"),
                   HM("attempts", "delivery_attempts", "delivery_id")],
        tags=["Deliveries"], realtime=True, transformer="business_delivery"),

    resource("packages", "One physical package inside a delivery.", [
        F("delivery_id", "integer", required=True, indexed=True),
        F("description", required=True, max_length=200),
        F("weight_kg", "number", required=True),
        F("length_cm", "number"), F("width_cm", "number"), F("height_cm", "number"),
        F("fragile", "boolean", default=False),
        money("declared_value_minor", default=0),
        F("photo_key", max_length=300),
        F("status", required=True, default="pending",
            enum=["pending", "loaded", "in_transit", "delivered", "returned", "damaged", "missing"]),
    ], OPS(list_=STAFF, get=STAFF, create=False, update=False, delete=False),
        relations=[BT("delivery", "delivery_requests", "delivery_id")], tags=["Deliveries"]),

    resource("delivery_attempts", "Every knock on the door: attempts, outcomes and what happens next.", [
        F("delivery_id", "integer", required=True, indexed=True),
        F("attempt", "integer", required=True),
        F("driver_user_id", required=True, indexed=True),
        F("outcome", required=True, enum=["recipient_unavailable", "address_issue", "refused",
                                          "access_denied", "success"]),
        F("note", "text"),
        F("photo_keys", "array", items={"type": "string"}, default=[]),
        F("action", required=True, enum=["retry_later", "contact_recipient", "wait", "reschedule",
                                         "alternate_address", "return_to_sender", "escalate", "none"]),
        F("next_attempt_ts", "integer"),
        F("alternate_address", "json"),
        lat(), lng(),
        ts("ts", required=True),
    ], OPS(list_=STAFF, get=STAFF, create=False, update=False, delete=False),
        relations=[BT("delivery", "delivery_requests", "delivery_id")], tags=["Deliveries"]),

    # ── routes and batches ───────────────────────────────────────────────────
    resource("delivery_routes", "A driver run covering many delivery stops.", [
        F("org_id", pattern="^[a-z0-9][a-z0-9-]{1,62}$", indexed=True),
        F("fleet_id", pattern="^[a-z0-9][a-z0-9-]{1,62}$", indexed=True),
        F("driver_user_id", indexed=True),
        F("driver_id", "integer"),
        F("vehicle_id", "integer"),
        F("market", required=True, indexed=True),
        F("status", required=True, default="planned", indexed=True,
            enum=["planned", "assigned", "active", "paused", "completed", "cancelled"]),
        F("stops_total", "integer", default=0),
        F("stops_completed", "integer", default=0),
        F("stops_failed", "integer", default=0),
        ts("started_ts"), ts("completed_ts"),
        F("notes", "text"),
    ], OPS(list_="staff_read", get="staff_read", create=False, update=False, delete=False),
        relations=[HM("stops", "route_stops", "route_id")], tags=["Routes"], realtime=True),

    resource("route_stops", "One delivery's place in a route, planned and actual.", [
        F("route_id", "integer", required=True, indexed=True),
        F("delivery_id", "integer", required=True, indexed=True),
        F("sequence_planned", "integer", required=True),
        F("sequence_actual", "integer"),
        F("status", required=True, default="pending",
            enum=["pending", "en_route", "arrived", "completed", "failed", "skipped"]),
        F("address", "json"),
        ts("arrived_ts"), ts("completed_ts"),
    ], OPS(list_=STAFF, get=STAFF, create=False, update=False, delete=False),
        relations=[BT("route", "delivery_routes", "route_id")], tags=["Routes"]),

    resource("delivery_batches", "A bulk delivery upload from a business, processed row by row.", [
        F("org_id", required=True, pattern="^[a-z0-9][a-z0-9-]{1,62}$", indexed=True),
        F("user_id", required=True, indexed=True),
        F("status", required=True, default="uploaded", indexed=True,
            enum=["uploaded", "validating", "processing", "completed", "completed_with_errors", "failed"]),
        F("total_rows", "integer", default=0),
        F("valid_rows", "integer", default=0),
        F("invalid_rows", "integer", default=0),
        F("dispatched_rows", "integer", default=0),
        F("failed_rows", "integer", default=0),
        F("errors", "json", default=[], description="[{row, reason}] — capped at 200"),
        F("rows", "json", description="The uploaded payload, kept for the processor"),
        ts("processed_ts"),
    ], OPS(list_="business_staff", get="business_staff", create=False, update=False, delete=False),
        tags=["Routes"]),

    # ── approvals ────────────────────────────────────────────────────────────
    resource("approvals", "A pending human decision that blocks a business process.", [
        F("subject_type", required=True, enum=["ride", "delivery", "refund", "payout"], indexed=True),
        F("subject_id", required=True, max_length=80, indexed=True),
        F("org_id", pattern="^[a-z0-9][a-z0-9-]{1,62}$", indexed=True),
        F("requested_by", required=True, max_length=120),
        money("amount_minor", default=0),
        F("reason", required=True, max_length=240),
        F("status", required=True, default="pending", indexed=True,
            enum=["pending", "approved", "rejected", "expired"]),
        F("decided_by", max_length=120),
        ts("decided_ts"),
        F("note", "text"),
        ts("due_ts", description="Auto-expiry for decisions that never arrive"),
    ], OPS(list_="approval_party", get="approval_party", create=False, update=False, delete=False),
        tags=["Approvals"], realtime=True),

    # ── chat ─────────────────────────────────────────────────────────────────
    resource("chat_messages", "In-app messaging between the parties of an active job.", [
        F("job_type", required=True, enum=["ride", "delivery"], indexed=True),
        F("job_id", "integer", required=True, indexed=True),
        F("user_id", required=True, indexed=True, description="The customer (denormalized)"),
        F("driver_user_id", indexed=True, description="The assigned driver (denormalized)"),
        F("sender_id", required=True, max_length=120),
        F("sender_role", required=True, max_length=40),
        F("body", required=True, max_length=2000),
        F("system", "boolean", default=False),
        F("read_ts", "integer"),
    ], OPS(list_=JOB_PARTY, get=JOB_PARTY, create=False, update=False, delete=False),
        tags=["Chat"], realtime=True),
]
