"""Every table keys on a ULID instead of an auto-increment integer.

Rebuilds the schema from the current models and carries every row across with
a new id, foreign keys rewritten (see ``pawabase_core.ulid_migration``).
Atomic: if anything fails the old tables are left as they were.
"""

from tortoise import migrations
from pawabase_core.ulid_migration import UlidRebuild
from tortoise.migrations import operations as ops
import functools
from database.fields import AnyJSONField
from json import dumps, loads
from pawabase_core.ids import new_ulid
from sillo.record.fields import CreatedAtField, SoftDeleteField, UpdatedAtField
from tortoise.fields.base import OnDelete
from uuid import uuid4
from tortoise import fields

# The schema after this migration: the models as they are now.
CREATES = [
    ops.CreateModel(
        name='AuditEntry',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('project', fields.CharField(null=True, db_index=True, max_length=63)),
            ('env', fields.CharField(null=True, max_length=63)),
            ('org', fields.CharField(null=True, db_index=True, max_length=63)),
            ('actor', fields.CharField(null=True, max_length=255)),
            ('action', fields.CharField(max_length=100)),
            ('target', fields.CharField(default='', max_length=255)),
            ('details', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
        ],
        options={'table': 'pb_audit', 'app': 'models', 'pk_attr': 'id', 'table_description': 'Who changed what on the management plane.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='EventLog',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('event_id', fields.CharField(unique=True, db_index=True, max_length=64)),
            ('project', fields.CharField(db_index=True, max_length=63)),
            ('env', fields.CharField(max_length=63)),
            ('name', fields.CharField(db_index=True, max_length=128)),
            ('source', fields.CharField(max_length=32)),
            ('actor', fields.CharField(null=True, max_length=255)),
            ('payload', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('request_id', fields.CharField(null=True, max_length=64)),
            ('occurred_at', fields.CharField(max_length=40)),
            ('consumers', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
        ],
        options={'table': 'pb_event_log', 'app': 'models', 'pk_attr': 'id', 'table_description': 'A published event and what consumed it.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='FailedJobRecord',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('job_id', fields.CharField(db_index=True, max_length=64)),
            ('queue', fields.CharField(db_index=True, max_length=128)),
            ('job_class', fields.CharField(max_length=255)),
            ('payload', fields.TextField(unique=False)),
            ('exception', fields.TextField(unique=False)),
            ('failed_at', fields.FloatField()),
        ],
        options={'table': 'pb_failed_jobs', 'app': 'models', 'pk_attr': 'id', 'table_description': "Sillo's failed-job store, persisted (see ``app.jobs.failed``)."},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='FlowRun',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, unique=True, db_index=True, max_length=32)),
            ('project', fields.CharField(db_index=True, max_length=63)),
            ('env', fields.CharField(max_length=63)),
            ('flow', fields.CharField(db_index=True, max_length=128)),
            ('trigger', fields.CharField(max_length=32)),
            ('status', fields.CharField(max_length=16)),
            ('input', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('output', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('error', fields.TextField(null=True, unique=False)),
            ('trace', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('logs', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('duration_ms', fields.FloatField(default=0)),
            ('request_id', fields.CharField(null=True, max_length=64)),
            ('job_id', fields.CharField(null=True, max_length=64)),
        ],
        options={'table': 'pb_flow_runs', 'app': 'models', 'pk_attr': 'id', 'table_description': 'One execution of a flow, with its step trace.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='FunctionRun',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, unique=True, db_index=True, max_length=32)),
            ('project', fields.CharField(db_index=True, max_length=63)),
            ('env', fields.CharField(db_index=True, max_length=63)),
            ('branch', fields.CharField(default='main', max_length=63)),
            ('function', fields.CharField(db_index=True, max_length=128)),
            ('deployment_id', fields.CharField(null=True, max_length=32)),
            ('trigger', fields.CharField(max_length=32)),
            ('status', fields.CharField(default='running', max_length=16)),
            ('input', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('output', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('error', fields.TextField(null=True, unique=False)),
            ('logs', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('duration_ms', fields.FloatField(null=True)),
            ('request_id', fields.CharField(null=True, max_length=128)),
            ('job_id', fields.CharField(null=True, max_length=128)),
        ],
        options={'table': 'pb_function_runs', 'app': 'models', 'pk_attr': 'id', 'table_description': 'An invocation record, including safe structured logs and failures.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='JobRun',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, unique=True, db_index=True, max_length=64)),
            ('project', fields.CharField(db_index=True, max_length=63)),
            ('env', fields.CharField(max_length=63)),
            ('queue', fields.CharField(db_index=True, max_length=128)),
            ('job', fields.CharField(max_length=128)),
            ('target', fields.CharField(default='', max_length=255)),
            ('source', fields.CharField(default='api', max_length=32)),
            ('request_id', fields.CharField(null=True, db_index=True, max_length=64)),
            ('status', fields.CharField(default='queued', db_index=True, max_length=16)),
            ('attempts', fields.IntField(default=0)),
            ('max_attempts', fields.IntField(default=1)),
            ('payload', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('result', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('error', fields.TextField(null=True, unique=False)),
            ('available_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ('started_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ('finished_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ('duration_ms', fields.FloatField(null=True)),
            ('worker', fields.CharField(null=True, max_length=128)),
        ],
        options={'table': 'pb_job_runs', 'app': 'models', 'pk_attr': 'id', 'table_description': "A queued job's lifecycle, recorded by job middleware for Studio."},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='MailLog',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('project', fields.CharField(db_index=True, max_length=63)),
            ('env', fields.CharField(max_length=63)),
            ('to', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('subject', fields.CharField(default='', max_length=255)),
            ('template', fields.CharField(null=True, max_length=128)),
            ('status', fields.CharField(max_length=16)),
            ('message_id', fields.CharField(null=True, max_length=255)),
            ('error', fields.TextField(null=True, unique=False)),
            ('source', fields.CharField(default='api', max_length=32)),
        ],
        options={'table': 'pb_mail_log', 'app': 'models', 'pk_attr': 'id', 'table_description': "A message sent (or suppressed) through an environment's mail settings."},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='MetricCounter',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('project', fields.CharField(db_index=True, max_length=63)),
            ('env', fields.CharField(max_length=63)),
            ('name', fields.CharField(db_index=True, max_length=128)),
            ('tags', fields.CharField(default='', max_length=512)),
            ('window', fields.DatetimeField(db_index=True, auto_now=False, auto_now_add=False)),
            ('value', fields.FloatField(default=0)),
            ('count', fields.IntField(default=0)),
        ],
        options={'table': 'pb_metrics', 'app': 'models', 'unique_together': (('project', 'env', 'name', 'tags', 'window'),), 'pk_attr': 'id', 'table_description': 'A per-minute counter written by ``metric.increment`` and platform code.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='Organization',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('slug', fields.CharField(unique=True, db_index=True, max_length=63)),
            ('name', fields.CharField(max_length=200)),
            ('created_by', fields.CharField(null=True, max_length=255)),
        ],
        options={'table': 'pb_organizations', 'app': 'models', 'pk_attr': 'id', 'table_description': 'A company or team. Members are platform operators, and projects belong to it.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='OrgInvitation',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('organization', fields.ForeignKeyField('models.Organization', source_field='organization_id', db_constraint=True, to_field='id', related_name='invitations', on_delete=OnDelete.CASCADE)),
            ('email', fields.CharField(db_index=True, max_length=255)),
            ('role', fields.CharField(default='developer', max_length=16)),
            ('token_hash', fields.CharField(unique=True, db_index=True, max_length=64)),
            ('invited_by', fields.CharField(null=True, max_length=255)),
            ('expires_at', fields.DatetimeField(auto_now=False, auto_now_add=False)),
            ('accepted_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ('revoked_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ('details', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
        ],
        options={'table': 'pb_org_invitations', 'app': 'models', 'pk_attr': 'id', 'table_description': "An invitation to join. Only the token's hash is stored."},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='OrgMember',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('organization', fields.ForeignKeyField('models.Organization', source_field='organization_id', db_constraint=True, to_field='id', related_name='members', on_delete=OnDelete.CASCADE)),
            ('user_id', fields.CharField(db_index=True, max_length=64)),
            ('email', fields.CharField(max_length=255)),
            ('name', fields.CharField(default='', max_length=200)),
            ('role', fields.CharField(default='developer', max_length=16)),
        ],
        options={'table': 'pb_org_members', 'app': 'models', 'unique_together': (('organization', 'user_id'),), 'pk_attr': 'id', 'table_description': 'An operator (an Akountz user of ``_platform``) in an organization.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='Project',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('ref', fields.CharField(unique=True, db_index=True, max_length=63)),
            ('name', fields.CharField(max_length=200)),
            ('description', fields.TextField(default='', unique=False)),
            ('created_by', fields.CharField(null=True, max_length=255)),
            ('organization', fields.ForeignKeyField('models.Organization', source_field='organization_id', null=True, description='The organization the project lives in. Every project has one, and the column', db_constraint=True, to_field='id', related_name='projects', on_delete=OnDelete.RESTRICT)),
        ],
        options={'table': 'pb_projects', 'app': 'models', 'pk_attr': 'id', 'table_description': 'One application backend.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='Environment',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('project', fields.ForeignKeyField('models.Project', source_field='project_id', db_constraint=True, to_field='id', related_name='environments', on_delete=OnDelete.CASCADE)),
            ('name', fields.CharField(max_length=63)),
            ('is_default', fields.BooleanField(default=False)),
            ('infra', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('auth', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('settings', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('version', fields.IntField(default=1)),
            ('preview_source', fields.CharField(null=True, description='Deploy previews are ordinary isolated environments with an automatic', max_length=63)),
            ('preview_expires_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
        ],
        options={'table': 'pb_environments', 'app': 'models', 'unique_together': (('project', 'name'),), 'pk_attr': 'id', 'table_description': 'An isolated stage of a project (``development``, ``production``…).'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='ApiVersion',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='api_versions', on_delete=OnDelete.CASCADE)),
            ('name', fields.CharField(max_length=32)),
            ('status', fields.CharField(default='draft', max_length=16)),
            ('is_default', fields.BooleanField(default=False)),
            ('active_release_id', fields.CharField(null=True, max_length=32)),
            ('previous_release_id', fields.CharField(null=True, max_length=32)),
            ('sunset_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
        ],
        options={'table': 'pb_api_versions', 'app': 'models', 'unique_together': (('environment', 'name'),), 'pk_attr': 'id', 'table_description': 'A stable public URL namespace such as ``v1`` or ``v2``.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='Branch',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='branches', on_delete=OnDelete.CASCADE)),
            ('name', fields.CharField(max_length=63)),
            ('head_revision_id', fields.CharField(null=True, max_length=32)),
            ('draft', AnyJSONField(default=dict, description='Mutable definition snapshot for an isolated working branch. ``main``', encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('base_snapshot', AnyJSONField(default=dict, description='Snapshot the branch started from, used for safe three-way merge checks.', encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('changes', AnyJSONField(default=list, description='Append-only authoring actions performed against this branch.', encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('protected', fields.BooleanField(default=False)),
        ],
        options={'table': 'pb_branches', 'app': 'models', 'unique_together': (('environment', 'name'),), 'pk_attr': 'id', 'table_description': 'A movable authoring pointer within one environment.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='Bucket',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('name', fields.CharField(max_length=128)),
            ('description', fields.TextField(default='', unique=False)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='buckets', on_delete=OnDelete.CASCADE)),
            ('public', fields.BooleanField(default=False)),
            ('read_policy', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('write_policy', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('accepts', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('max_bytes', fields.BigIntField(default=0)),
            ('signed_uploads', fields.BooleanField(default=True)),
        ],
        options={'table': 'pb_buckets', 'app': 'models', 'unique_together': (('environment', 'name'),), 'pk_attr': 'id', 'table_description': "A storage bucket in the environment's storage."},
        bases=['_Definition'],
    ),
    ops.CreateModel(
        name='DefinitionRevision',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, unique=True, db_index=True, max_length=32)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='revisions', on_delete=OnDelete.CASCADE)),
            ('number', fields.IntField()),
            ('branch', fields.CharField(default='main', max_length=63)),
            ('parent_revision_id', fields.CharField(null=True, max_length=32)),
            ('checksum', fields.CharField(db_index=True, max_length=64)),
            ('snapshot', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('status', fields.CharField(default='valid', max_length=16)),
            ('problems', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('message', fields.TextField(default='', unique=False)),
            ('created_by', fields.CharField(null=True, max_length=255)),
        ],
        options={'table': 'pb_definition_revisions', 'app': 'models', 'unique_together': (('environment', 'number'),), 'pk_attr': 'id', 'table_description': "An immutable, validated snapshot of an environment's definitions."},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='Deployment',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='deployments', on_delete=OnDelete.CASCADE)),
            ('api_version', fields.CharField(db_index=True, max_length=32)),
            ('release_id', fields.CharField(max_length=32)),
            ('previous_release_id', fields.CharField(null=True, max_length=32)),
            ('action', fields.CharField(max_length=16)),
            ('status', fields.CharField(default='succeeded', max_length=16)),
            ('actor', fields.CharField(null=True, max_length=255)),
            ('details', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
        ],
        options={'table': 'pb_deployments', 'app': 'models', 'pk_attr': 'id', 'table_description': 'Append-only history of activations and rollbacks.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='EventSubscription',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('name', fields.CharField(max_length=128)),
            ('description', fields.TextField(default='', unique=False)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='subscriptions', on_delete=OnDelete.CASCADE)),
            ('event', fields.CharField(max_length=128)),
            ('target_type', fields.CharField(max_length=16)),
            ('target', fields.CharField(default='', max_length=255)),
            ('condition', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('enabled', fields.BooleanField(default=True)),
        ],
        options={'table': 'pb_event_subscriptions', 'app': 'models', 'unique_together': (('environment', 'name'),), 'pk_attr': 'id', 'table_description': 'Connects events to consumers.'},
        bases=['_Definition'],
    ),
    ops.CreateModel(
        name='Flow',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('name', fields.CharField(max_length=128)),
            ('description', fields.TextField(default='', unique=False)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='flows', on_delete=OnDelete.CASCADE)),
            ('definition', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('enabled', fields.BooleanField(default=True)),
            ('timeout', fields.FloatField(default=60.0)),
            ('record_runs', fields.BooleanField(default=True)),
        ],
        options={'table': 'pb_flows', 'app': 'models', 'unique_together': (('environment', 'name'),), 'pk_attr': 'id', 'table_description': 'A visual backend flow (``@xyflow/react`` nodes and edges).'},
        bases=['_Definition'],
    ),
    ops.CreateModel(
        name='FunctionDeployment',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, unique=True, db_index=True, max_length=32)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='function_deployments', on_delete=OnDelete.CASCADE)),
            ('branch', fields.CharField(default='main', db_index=True, max_length=63)),
            ('checksum', fields.CharField(db_index=True, max_length=64)),
            ('status', fields.CharField(default='building', max_length=16)),
            ('runtime', fields.CharField(default='python3.11', max_length=64)),
            ('entrypoint', fields.CharField(default='functions', max_length=255)),
            ('manifest', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('limits', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('error', fields.TextField(default='', unique=False)),
            ('activated_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ('removed_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ('created_by', fields.CharField(null=True, max_length=255)),
        ],
        options={'table': 'pb_function_deployments', 'app': 'models', 'pk_attr': 'id', 'table_description': 'One uploaded, content-addressed Functions artifact for an environment.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='InboundHook',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('name', fields.CharField(max_length=128)),
            ('description', fields.TextField(default='', unique=False)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='inbound_hooks', on_delete=OnDelete.CASCADE)),
            ('slug', fields.CharField(max_length=128)),
            ('verification', fields.CharField(default='hmac-sha256', max_length=20)),
            ('signature_header', fields.CharField(default='x-signature', max_length=128)),
            ('secret_ciphertext', fields.TextField(null=True, unique=False)),
            ('target_type', fields.CharField(default='event', max_length=16)),
            ('target', fields.CharField(max_length=255)),
            ('enabled', fields.BooleanField(default=True)),
            ('received', fields.IntField(default=0)),
            ('last_received_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
        ],
        options={'table': 'pb_inbound_hooks', 'app': 'models', 'unique_together': (('environment', 'slug'),), 'pk_attr': 'id', 'table_description': 'An inbound webhook: a URL third parties call.'},
        bases=['_Definition'],
    ),
    ops.CreateModel(
        name='MailTemplate',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('name', fields.CharField(max_length=128)),
            ('description', fields.TextField(default='', unique=False)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='mail_templates', on_delete=OnDelete.CASCADE)),
            ('subject', fields.CharField(default='', max_length=255)),
            ('html', fields.TextField(default='', unique=False)),
            ('text', fields.TextField(default='', unique=False)),
        ],
        options={'table': 'pb_mail_templates', 'app': 'models', 'unique_together': (('environment', 'name'),), 'pk_attr': 'id', 'table_description': "A stored email template, rendered in Jinja2's sandbox."},
        bases=['_Definition'],
    ),
    ops.CreateModel(
        name='PolicyDef',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('name', fields.CharField(max_length=128)),
            ('description', fields.TextField(default='', unique=False)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='policies', on_delete=OnDelete.CASCADE)),
            ('condition', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
        ],
        options={'table': 'pb_policies', 'app': 'models', 'unique_together': (('environment', 'name'),), 'pk_attr': 'id', 'table_description': 'A reusable policy condition.'},
        bases=['_Definition'],
    ),
    ops.CreateModel(
        name='ProjectKey',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='keys', on_delete=OnDelete.CASCADE)),
            ('name', fields.CharField(max_length=200)),
            ('role', fields.CharField(default='publishable', max_length=20)),
            ('prefix', fields.CharField(max_length=24)),
            ('key_hash', fields.CharField(unique=True, db_index=True, max_length=128)),
            ('scopes', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('allowed_ips', AnyJSONField(default=list, description='CIDRs and route rules evaluated by the public gateway before proxying.', encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('allowed_routes', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('expires_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ('revoked_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ('last_used_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ('use_count', fields.IntField(default=0)),
            ('created_by', fields.CharField(null=True, max_length=255)),
        ],
        options={'table': 'pb_project_keys', 'app': 'models', 'pk_attr': 'id', 'table_description': 'An API key for one environment.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='Release',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, unique=True, db_index=True, max_length=32)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='releases', on_delete=OnDelete.CASCADE)),
            ('revision_id', fields.CharField(db_index=True, max_length=32)),
            ('api_version', fields.CharField(db_index=True, max_length=32)),
            ('name', fields.CharField(max_length=128)),
            ('status', fields.CharField(default='ready', max_length=16)),
            ('notes', fields.TextField(default='', unique=False)),
            ('compatibility', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('created_by', fields.CharField(null=True, max_length=255)),
            ('deployed_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
        ],
        options={'table': 'pb_releases', 'app': 'models', 'pk_attr': 'id', 'table_description': 'A revision prepared for, or active on, one public API version.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='RequestLog',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('request_id', fields.CharField(db_index=True, max_length=64)),
            ('service', fields.CharField(db_index=True, max_length=32)),
            ('project', fields.CharField(db_index=True, max_length=63)),
            ('env', fields.CharField(db_index=True, max_length=63)),
            ('method', fields.CharField(max_length=16)),
            ('path', fields.TextField(unique=False)),
            ('route', fields.CharField(null=True, max_length=512)),
            ('status', fields.IntField(db_index=True)),
            ('duration_ms', fields.FloatField(default=0)),
            ('started_at', fields.CharField(db_index=True, max_length=40)),
            ('role', fields.CharField(null=True, max_length=64)),
            ('user', fields.CharField(null=True, max_length=255)),
            ('ip', fields.CharField(null=True, max_length=64)),
            ('user_agent', fields.TextField(null=True, unique=False)),
            ('error', fields.TextField(null=True, unique=False)),
            ('notes', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
        ],
        options={'table': 'pb_request_logs', 'app': 'models', 'pk_attr': 'id', 'table_description': 'One persisted data-plane request and its structured trace notes.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='Resource',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('name', fields.CharField(max_length=128)),
            ('description', fields.TextField(default='', unique=False)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='resources', on_delete=OnDelete.CASCADE)),
            ('table', fields.CharField(max_length=128)),
            ('primary_key', fields.CharField(default='id', max_length=64)),
            ('id_type', fields.CharField(default='integer', max_length=16)),
            ('fields_', AnyJSONField(source_field='fields', default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('operations', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('relations', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('transformer', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('cache_ttl', fields.IntField(default=0)),
            ('rate_limit', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('events', fields.BooleanField(default=True)),
            ('realtime', fields.BooleanField(default=False)),
            ('timestamps', fields.BooleanField(default=True)),
            ('owner_field', fields.CharField(null=True, max_length=64)),
            ('tags', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
        ],
        options={'table': 'pb_resources', 'app': 'models', 'unique_together': (('environment', 'name'),), 'pk_attr': 'id', 'table_description': 'An application entity and its backend behaviour.'},
        bases=['_Definition'],
    ),
    ops.CreateModel(
        name='RouteDef',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('name', fields.CharField(max_length=128)),
            ('description', fields.TextField(default='', unique=False)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='routes', on_delete=OnDelete.CASCADE)),
            ('method', fields.CharField(default='POST', max_length=10)),
            ('path', fields.CharField(max_length=255)),
            ('policy', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('input_fields', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('input_schema', fields.CharField(null=True, max_length=128)),
            ('response_schema', fields.CharField(null=True, max_length=128)),
            ('transformer', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('handler_type', fields.CharField(default='flow', max_length=16)),
            ('handler', fields.CharField(max_length=128)),
            ('rate_limit', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('cache_ttl', fields.IntField(default=0)),
            ('tags', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('enabled', fields.BooleanField(default=True)),
        ],
        options={'table': 'pb_routes', 'app': 'models', 'unique_together': (('environment', 'method', 'path'),), 'pk_attr': 'id', 'table_description': 'A custom API route served by a flow or a Python function.'},
        bases=['_Definition'],
    ),
    ops.CreateModel(
        name='Schedule',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('name', fields.CharField(max_length=128)),
            ('description', fields.TextField(default='', unique=False)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='schedules', on_delete=OnDelete.CASCADE)),
            ('cron', fields.CharField(null=True, max_length=64)),
            ('interval_seconds', fields.IntField(null=True)),
            ('target_type', fields.CharField(max_length=16)),
            ('target', fields.CharField(max_length=255)),
            ('payload', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('enabled', fields.BooleanField(default=True)),
            ('last_run_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ('last_status', fields.CharField(null=True, max_length=20)),
            ('run_count', fields.IntField(default=0)),
        ],
        options={'table': 'pb_schedules', 'app': 'models', 'unique_together': (('environment', 'name'),), 'pk_attr': 'id', 'table_description': "Scheduled work, run by Sillo's scheduler in the scheduler process."},
        bases=['_Definition'],
    ),
    ops.CreateModel(
        name='SchemaDef',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('name', fields.CharField(max_length=128)),
            ('description', fields.TextField(default='', unique=False)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='schemas', on_delete=OnDelete.CASCADE)),
            ('fields_', AnyJSONField(source_field='fields', default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
        ],
        options={'table': 'pb_schemas', 'app': 'models', 'unique_together': (('environment', 'name'),), 'pk_attr': 'id', 'table_description': 'A reusable schema: field definitions (see ``pawabase_core.schemas``).'},
        bases=['_Definition'],
    ),
    ops.CreateModel(
        name='Secret',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='secrets', on_delete=OnDelete.CASCADE)),
            ('name', fields.CharField(max_length=128)),
            ('ciphertext', fields.TextField(unique=False)),
            ('description', fields.TextField(default='', unique=False)),
            ('updated_by', fields.CharField(null=True, max_length=255)),
        ],
        options={'table': 'pb_secrets', 'app': 'models', 'unique_together': (('environment', 'name'),), 'pk_attr': 'id', 'table_description': 'An encrypted configuration value. Its plaintext never leaves the API.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='TransformerDef',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('name', fields.CharField(max_length=128)),
            ('description', fields.TextField(default='', unique=False)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='transformers', on_delete=OnDelete.CASCADE)),
            ('definition', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
        ],
        options={'table': 'pb_transformers', 'app': 'models', 'unique_together': (('environment', 'name'),), 'pk_attr': 'id', 'table_description': 'A reusable declarative transformer.'},
        bases=['_Definition'],
    ),
    ops.CreateModel(
        name='WebhookEndpoint',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('name', fields.CharField(max_length=128)),
            ('description', fields.TextField(default='', unique=False)),
            ('environment', fields.ForeignKeyField('models.Environment', source_field='environment_id', db_constraint=True, to_field='id', related_name='webhooks', on_delete=OnDelete.CASCADE)),
            ('url', fields.CharField(max_length=2048)),
            ('events', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('secret_ciphertext', fields.TextField(unique=False)),
            ('headers', AnyJSONField(default=dict, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('enabled', fields.BooleanField(default=True)),
            ('max_attempts', fields.IntField(default=5)),
        ],
        options={'table': 'pb_webhooks', 'app': 'models', 'unique_together': (('environment', 'name'),), 'pk_attr': 'id', 'table_description': 'An outbound webhook: events POSTed, signed, to a URL.'},
        bases=['_Definition'],
    ),
    ops.CreateModel(
        name='WebhookDelivery',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('endpoint', fields.ForeignKeyField('models.WebhookEndpoint', source_field='endpoint_id', db_constraint=True, to_field='id', related_name='deliveries', on_delete=OnDelete.CASCADE)),
            ('event_id', fields.CharField(db_index=True, max_length=64)),
            ('event', fields.CharField(max_length=128)),
            ('payload', AnyJSONField(null=True, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('status', fields.CharField(default='pending', max_length=16)),
            ('attempts', fields.IntField(default=0)),
            ('response_status', fields.IntField(null=True)),
            ('response_body', fields.TextField(null=True, unique=False)),
            ('error', fields.TextField(null=True, unique=False)),
            ('duration_ms', fields.FloatField(null=True)),
            ('delivered_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
        ],
        options={'table': 'pb_webhook_deliveries', 'app': 'models', 'pk_attr': 'id', 'table_description': 'One attempt series to deliver an event to an outbound webhook.'},
        bases=['Model'],
    ),
    ops.CreateModel(
        name='WorkerHeartbeat',
        fields=[
            ('created_at', CreatedAtField()),
            ('updated_at', UpdatedAtField()),
            ('deleted_at', SoftDeleteField(null=True)),
            ('id', fields.CharField(primary_key=True, default=new_ulid, unique=True, db_index=True, max_length=26)),
            ('name', fields.CharField(unique=True, max_length=255)),
            ('kind', fields.CharField(default='worker', max_length=16)),
            ('queues', AnyJSONField(default=list, encoder=functools.partial(dumps, separators=(',', ':')), decoder=loads)),
            ('status', fields.CharField(default='running', max_length=16)),
            ('concurrency', fields.IntField(default=1)),
            ('processed', fields.IntField(default=0)),
            ('started_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ('last_seen', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
        ],
        options={'table': 'pb_workers', 'app': 'models', 'pk_attr': 'id', 'table_description': 'A queue worker or scheduler process, as last seen.'},
        bases=['Model'],
    ),
]


class Migration(migrations.Migration):
    dependencies = [('models', '0008_function_branches')]

    initial = False

    operations = UlidRebuild(CREATES).operations()
